{% set name = "fscacher" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4581be4e2ab02bd6b3784981f2726b782d2574f2a5e109d2581e0bf55726e991

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - joblib
    - platformdirs

test:
  requires:
    - pytest
    - pytest-mock
    - python {{ python_min }}
  imports:
    - fscacher
    - fscacher.tests
  commands:
    - python -m pytest -vv --pyargs fscacher

about:
  home: https://github.com/con/fscacher
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Caching results of operations on heavy file trees
  description: |
    fscacher provides a cache & decorator for memoizing functions whose outputs
    depend upon the contents of a file argument.
  dev_url: https://github.com/con/fscacher
  doc_url: https://pypi.org/project/fscacher/

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
